# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

target 'GoodApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  react_native_path = "../node_modules/react-native"
  yoga_path = File.join(react_native_path, 'ReactCommon/yoga')

  pod "Yoga", :path => yoga_path

  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'


  pod 'Firebase/Messaging'

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'Google/SignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


end
